USE [HandbookNew]
GO

/****** Object:  Table [dbo].[Menu]    Script Date: 8/2/2017 4:31:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Menu](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[ParentID] [int] NULL,
 CONSTRAINT [PK_MEnu] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Menu]  WITH CHECK ADD  CONSTRAINT [Parent] FOREIGN KEY([ParentID])
REFERENCES [dbo].[Menu] ([ID])
GO

ALTER TABLE [dbo].[Menu] CHECK CONSTRAINT [Parent]
GO


